version: '3.7'

services:
    db:
        image: postgres:11
        container_name: crud_go_db
        ports:
            - 32705:5432
        volumes:
            - ./db_data:/var/lib/postgresql/db_data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: musicstore